#!/usr/bin/env python3
"""Regenerate the [exclude-newer-package] table in uv.toml.

The global ``exclude-newer`` cutoff in ``uv.toml`` skips package versions
published within the last few days as a supply-chain safeguard. First-party
packages should be exempt from that cutoff so freshly released versions can be
installed immediately.

This script rewrites ``uv.toml`` so the ``[exclude-newer-package]`` table
always contains ``haystack-ai`` plus every package maintained in
https://github.com/deepset-ai/haystack-core-integrations . The integration
package names are read from the ``name`` field of each
``integrations/*/pyproject.toml`` in a local checkout of that repository.

Usage:
    python scripts/generate_uv_excludes.py \
        --integrations-repo /path/to/haystack-core-integrations \
        --uv-toml uv.toml [--check]

With ``--check`` the script does not write anything and exits non-zero if the
file is out of date (useful in CI).
"""

import argparse
import re
import sys
from pathlib import Path

# Packages that are first-party but not part of haystack-core-integrations.
ALWAYS_INCLUDE = ["haystack-ai"]

HEADER = """\
# Exclude package versions published within the last 3 days to protect against supply chain
# attacks via compromised dependencies.
exclude-newer = "P3D"

# first-party dependencies can be excluded from the global cutoff by adding entries below.
# This includes haystack-ai and all packages maintained in
# https://github.com/deepset-ai/haystack-core-integrations
#
# NOTE: the integration entries are generated by scripts/generate_uv_excludes.py
# and kept in sync by the "Sync uv excludes" GitHub Actions workflow. Edit the
# script rather than this list by hand.
[exclude-newer-package]
"""

NAME_RE = re.compile(r'^name\s*=\s*"([^"]+)"', re.MULTILINE)


def normalize(name: str) -> str:
    """Normalize a distribution name to PEP 503 form (lowercase, hyphens)."""
    return re.sub(r"[-_.]+", "-", name).lower()


def collect_integration_names(integrations_repo: Path) -> list[str]:
    integrations_dir = integrations_repo / "integrations"
    if not integrations_dir.is_dir():
        sys.exit(f"error: {integrations_dir} not found; is --integrations-repo correct?")

    names = set()
    for pyproject in integrations_dir.glob("*/pyproject.toml"):
        text = pyproject.read_text(encoding="utf-8")
        match = NAME_RE.search(text)
        if match:
            names.add(normalize(match.group(1)))
    if not names:
        sys.exit(f"error: no package names found under {integrations_dir}")
    return sorted(names)


def render(names: list[str]) -> str:
    lines = [HEADER]
    for pkg in ALWAYS_INCLUDE:
        lines.append(f"{normalize(pkg)} = false\n")
    for pkg in names:
        if normalize(pkg) in {normalize(p) for p in ALWAYS_INCLUDE}:
            continue
        lines.append(f"{pkg} = false\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--integrations-repo",
        type=Path,
        required=True,
        help="Path to a local checkout of deepset-ai/haystack-core-integrations",
    )
    parser.add_argument("--uv-toml", type=Path, default=Path("uv.toml"), help="Path to uv.toml to write")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if uv.toml is out of date",
    )
    args = parser.parse_args()

    names = collect_integration_names(args.integrations_repo)
    content = render(names)

    current = args.uv_toml.read_text(encoding="utf-8") if args.uv_toml.exists() else ""
    if current == content:
        print(f"{args.uv_toml} is up to date ({len(names)} integration packages).")
        return 0

    if args.check:
        print(f"{args.uv_toml} is OUT OF DATE. Run generate_uv_excludes.py to update it.", file=sys.stderr)
        return 1

    args.uv_toml.write_text(content, encoding="utf-8")
    print(f"Wrote {args.uv_toml} with {len(names)} integration packages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
