name: Sync all tutorials with dC workspace

on:
  workflow_dispatch:

jobs:
  full_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          uv venv
          uv pip install --exclude-newer P3D -r requirements.txt

      - name: Generate all tutorials and their metadata
        run: |
          . .venv/bin/activate
          python scripts/generate_txt.py --notebooks all --metadata

      - name: Full sync
        env:
          DEEPSET_CLOUD_WORKSPACE: ${{ secrets.DEEPSET_CLOUD_WORKSPACE }}
          DEEPSET_CLOUD_API_KEY: ${{ secrets.DEEPSET_CLOUD_API_KEY }}
        run: |
          . .venv/bin/activate
          python scripts/full_dc_sync.py
