name: Run Tutorials Nightly

on:
  workflow_dispatch: # Activate this workflow manually
  schedule:
    - cron: "0 0 * * *"
  # TODO: REMOVE TRIGGER AFTER TESTING
  pull_request:

jobs:
  generate-matrix:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.generator.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - id: generator
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get tutorial notebooks
          VERSION=$(gh api /repos/deepset-ai/haystack/releases | \
            jq -r '[.[].tag_name | select(test("^v2.[0-9]+.[0-9]+$"))] | first')
          NOTEBOOKS=$(python ./scripts/generate_matrix.py --haystack-version "$VERSION" --include-main)
          echo "matrix={\"include\":$NOTEBOOKS}" >> "$GITHUB_OUTPUT"

  run-tutorials:
    needs: generate-matrix
    runs-on: ubuntu-latest
    container: deepset/haystack:base-${{ matrix.haystack_version }}

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}

    env:
      HAYSTACK_TELEMETRY_ENABLED: "False"
      HF_API_TOKEN: ${{ secrets.HF_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SERPERDEV_API_KEY: ${{ secrets.SERPERDEV_API_KEY }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"

      - name: Install common dependencies
        run: |
          apt-get update && apt-get install -y \
              build-essential \
              gcc \
              libsndfile1 \
              ffmpeg
          
          uv venv
          uv pip install nbconvert ipython

      - name: Install tutorial dependencies
        if: toJSON(matrix.dependencies) != '[]'
        run: |
          uv pip install "${{ join(matrix.dependencies, '" "')}}"

      - name: Convert notebook to Python
        run: |
          source .venv/bin/activate
          jupyter nbconvert --to python --RegexRemovePreprocessor.patterns '%%bash' ./tutorials/${{ matrix.notebook }}.ipynb

      - name: Run the converted notebook
        run: |
          source .venv/bin/activate
          NOTEBOOK="./tutorials/${{ matrix.notebook }}.py"
          if [ "${{ matrix.notebook }}" = "47_Human_in_the_Loop_Agent" ]; then
            # We add a prompt to confirm any user inputs in the HiTL notebook
            yes y | python "$NOTEBOOK"
          elif [ "${{ matrix.notebook }}" = "48_Conversational_RAG" ]; then
            yes Q | python "$NOTEBOOK"
          else
            python "$NOTEBOOK"
          fi

      # - name: Notify Slack on nightly failure
      #   if: failure()
      #   uses: deepset-ai/notify-slack-action@v1
      #   with:
      #     slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFICATIONS }}
      #     mention-here: false
