name: Verify tutorials generation

on:
  pull_request:
    paths:
      - "tutorials/*.ipynb"
      - "index.toml"

jobs:
  verify-markdown-generation:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt

      - name: Generate all tutorials
        run: |
          . .venv/bin/activate
          mkdir output
          python scripts/generate_markdowns.py --index index.toml --notebooks all --output ./output
